"""Update Profile

Revision ID: 70ccb0e18605
Revises: 
Create Date: 2022-09-20 07:02:05.509343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70ccb0e18605'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('birthplace', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('nationality', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('religion', sa.String(), nullable=True))
    op.drop_column('profiles', 'skills')
    op.drop_column('profiles', 'seminars')
    op.drop_column('profiles', 'fathersname')
    op.drop_column('profiles', 'mothersname')
    op.drop_column('profiles', 'hobbies')
    op.drop_column('profiles', 'awards')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('awards', sa.VARCHAR(), nullable=True))
    op.add_column('profiles', sa.Column('hobbies', sa.VARCHAR(), nullable=True))
    op.add_column('profiles', sa.Column('mothersname', sa.VARCHAR(), nullable=True))
    op.add_column('profiles', sa.Column('fathersname', sa.VARCHAR(), nullable=True))
    op.add_column('profiles', sa.Column('seminars', sa.VARCHAR(), nullable=True))
    op.add_column('profiles', sa.Column('skills', sa.VARCHAR(), nullable=True))
    op.drop_column('profiles', 'religion')
    op.drop_column('profiles', 'nationality')
    op.drop_column('profiles', 'birthplace')
    # ### end Alembic commands ###
